#!/usr/bin/env bash
# Drive the app on a local Android emulator (or a plugged-in device) without Android Studio.
#
#   scripts/android.sh up        boot emulator → build → install → metro → launch  (default)
#   scripts/android.sh build     gradle assembleDebug only
#   scripts/android.sh install   install the last built APK
#   scripts/android.sh launch    (re)start the app on the device
#   scripts/android.sh metro     start the Metro dev server in the background
#   scripts/android.sh reset     wipe the app's data (fresh DB — the "no рахунок yet" state)
#   scripts/android.sh shot F    screenshot the device into file F (default .cache/android/shot.png)
#   scripts/android.sh tap X Y   tap at device pixels (a screenshot is 1:1 with them)
#   scripts/android.sh text S    type S into the focused field
#   scripts/android.sh key K     a key event: back, enter, tab, del …
#   scripts/android.sh logs      tail the app's JS/native log
#   scripts/android.sh stop      stop Metro and the Gradle daemon
#
# `android/` is generated by `expo prebuild` and gitignored; this script regenerates it when
# missing. Never hand-edit it (see .claude/rules/android.md).
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$PWD

PACKAGE=com.antonbabychp1t.cap1tal
AVD=${CAP1TAL_AVD:-Pixel_10_Pro}
METRO_PORT=${RCT_METRO_PORT:-8081}
RUN_DIR=.cache/android
APK=android/app/build/outputs/apk/debug/app-debug.apk

export ANDROID_HOME=${ANDROID_HOME:-$HOME/Library/Android/sdk}
export ANDROID_SDK_ROOT=$ANDROID_HOME
# AGP needs a JDK it knows; the machine default may be newer than Gradle supports.
export JAVA_HOME=${JAVA_HOME:-$(/usr/libexec/java_home -v 21 2>/dev/null || echo "/Applications/Android Studio.app/Contents/jbr/Contents/Home")}
export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"

mkdir -p "$RUN_DIR"
say() { printf '\033[36m▸ %s\033[0m\n' "$*"; }
die() { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

serial() { adb devices | awk '/\tdevice$/ {print $1; exit}'; }

ensure_device() {
  local s
  s=$(serial)
  if [ -z "$s" ]; then
    say "no device attached — booting AVD $AVD"
    command -v emulator >/dev/null || die "emulator binary missing; install it in Android Studio → SDK Tools"
    emulator -avd "$AVD" -netdelay none -netspeed full >"$RUN_DIR/emulator.log" 2>&1 &
    adb wait-for-device
    until [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" = 1 ]; do sleep 2; done
    s=$(serial)
  fi
  export ANDROID_SERIAL=$s
  say "device $ANDROID_SERIAL ($(adb shell getprop ro.product.model | tr -d '\r'), API $(adb shell getprop ro.build.version.sdk | tr -d '\r'))"
}

ensure_native() {
  [ -d android ] || { say "android/ missing — running expo prebuild"; npx expo prebuild --platform android --no-install; git checkout -- package.json 2>/dev/null || true; }
}

build() {
  ensure_native
  # Only the ABI the device actually uses — a four-ABI build is ~4× the work.
  local abi; abi=$(adb shell getprop ro.product.cpu.abi 2>/dev/null | tr -d '\r'); abi=${abi:-arm64-v8a}
  say "gradle assembleDebug ($abi)"
  (cd android && ./gradlew assembleDebug -PreactNativeArchitectures="$abi" --console=plain)
}

install() {
  [ -f "$APK" ] || build
  say "installing $APK"
  adb install -r -d "$APK"
}

metro() {
  if curl -s "http://localhost:$METRO_PORT/status" 2>/dev/null | grep -q packager; then
    say "Metro already running on $METRO_PORT"
  else
    say "starting Metro (log: $RUN_DIR/metro.log)"
    npx expo start --port "$METRO_PORT" >"$RUN_DIR/metro.log" 2>&1 &
    echo $! >"$RUN_DIR/metro.pid"
    until curl -s "http://localhost:$METRO_PORT/status" 2>/dev/null | grep -q packager; do sleep 1; done
  fi
  # The debug build fetches its bundle from localhost on the device.
  adb reverse "tcp:$METRO_PORT" "tcp:$METRO_PORT" >/dev/null
}

launch() {
  say "launching $PACKAGE"
  adb shell am force-stop "$PACKAGE"
  adb shell monkey -p "$PACKAGE" -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1
}

case "${1:-up}" in
  up)      ensure_device; install; metro; launch; say "up — screenshot with: scripts/android.sh shot" ;;
  build)   ensure_device; build ;;
  install) ensure_device; install ;;
  metro)   ensure_device; metro ;;
  launch)  ensure_device; launch ;;
  reset)   ensure_device; say "clearing app data"; adb shell pm clear "$PACKAGE"; launch ;;
  shot)    ensure_device; out=${2:-$RUN_DIR/shot.png}; adb exec-out screencap -p >"$out"; say "wrote $out" ;;
  tap)     ensure_device; adb shell input tap "${2:?x}" "${3:?y}" ;;
  # `input text` takes no spaces and no Cyrillic; %s stands in for a space, and non-ASCII goes
  # through the IME clipboard instead. Keep smoke-test input ASCII where you can.
  text)    ensure_device; adb shell input text "$(printf '%s' "${2:?text}" | sed 's/ /%s/g')" ;;
  key)     ensure_device; adb shell input keyevent "${2:?keycode}" ;;
  logs)    ensure_device; adb logcat -s ReactNative:V ReactNativeJS:V AndroidRuntime:E expo:V ;;
  stop)    [ -f "$RUN_DIR/metro.pid" ] && kill "$(cat "$RUN_DIR/metro.pid")" 2>/dev/null || true
           rm -f "$RUN_DIR/metro.pid"; (cd android 2>/dev/null && ./gradlew --stop) || true; say "stopped" ;;
  *)       die "unknown command: $1 (see the header of $0)" ;;
esac
