#!/usr/bin/env bash
# Drive the app on a local Android emulator (or a plugged-in device) without Android Studio.
#
#   scripts/android.sh up        boot emulator → build → install → metro → launch  (default)
#   scripts/android.sh build     gradle assembleDebug only
#   scripts/android.sh install   install the last built APK
#   scripts/android.sh launch    (re)start the app on the device
#   scripts/android.sh metro     start the Metro dev server in the background
#   scripts/android.sh reset     wipe the app's data (fresh DB — the "no рахунок yet" state)
#   scripts/android.sh shot F    screenshot the device into file F (default .cache/android/shot.png)
#   scripts/android.sh tap X Y   tap at device pixels (a screenshot is 1:1 with them)
#   scripts/android.sh text S    type S into the focused field
#   scripts/android.sh key K     a key event: back, enter, tab, del …
#   scripts/android.sh swipe X1 Y1 X2 Y2 [MS]      one finger, dragged (scrolling, flicks)
#   scripts/android.sh twofinger X1 Y1 X2 Y2 [MS]  two fingers held STILL (the репорт gesture)
#   scripts/android.sh twodrag X1 Y1 X2 Y2 DX DY [MS]  two fingers dragged (must start nothing)
#   scripts/android.sh logs [N]  dump the last N (200) lines of the app's JS/native log and exit
#   scripts/android.sh stop      stop Metro and the Gradle daemon
#
# `android/` is generated by `expo prebuild` and gitignored; this script regenerates it when
# missing. Never hand-edit it (see .claude/rules/android.md).
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$PWD

PACKAGE=com.antonbabychp1t.cap1tal
AVD=${CAP1TAL_AVD:-Pixel_10_Pro}
METRO_PORT=${RCT_METRO_PORT:-8081}
RUN_DIR=.cache/android
APK=android/app/build/outputs/apk/debug/app-debug.apk

export ANDROID_HOME=${ANDROID_HOME:-$HOME/Library/Android/sdk}
export ANDROID_SDK_ROOT=$ANDROID_HOME
# AGP needs a JDK it knows; the machine default may be newer than Gradle supports.
export JAVA_HOME=${JAVA_HOME:-$(/usr/libexec/java_home -v 21 2>/dev/null || echo "/Applications/Android Studio.app/Contents/jbr/Contents/Home")}
export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"

mkdir -p "$RUN_DIR"
say() { printf '\033[36m▸ %s\033[0m\n' "$*"; }
die() { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

serial() { adb devices | awk '/\tdevice$/ {print $1; exit}'; }

ensure_device() {
  local s
  s=$(serial)
  if [ -z "$s" ]; then
    say "no device attached — booting AVD $AVD"
    command -v emulator >/dev/null || die "emulator binary missing; install it in Android Studio → SDK Tools"
    emulator -avd "$AVD" -netdelay none -netspeed full >"$RUN_DIR/emulator.log" 2>&1 &
    adb wait-for-device
    until [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" = 1 ]; do sleep 2; done
    s=$(serial)
  fi
  export ANDROID_SERIAL=$s
  say "device $ANDROID_SERIAL ($(adb shell getprop ro.product.model | tr -d '\r'), API $(adb shell getprop ro.build.version.sdk | tr -d '\r'))"
}

# `expo prebuild` is what carries app.json and plugins/ into android/ — a new permission, a new
# config plugin or a new native module reaches the manifest no other way. It also rewrites
# package.json's scripts, which is undone afterwards: with `git stash` semantics, because a plain
# `git checkout -- package.json` would throw away an uncommitted dependency the change just added.
prebuild() {
  say "expo prebuild (android)"
  local dirty=; git diff --quiet -- package.json 2>/dev/null || dirty=1
  local keep=$RUN_DIR/package.json.before-prebuild
  [ -n "$dirty" ] && cp package.json "$keep"
  npx expo prebuild --platform android --no-install
  if [ -n "$dirty" ]; then cp "$keep" package.json; rm -f "$keep"
  else git checkout -- package.json 2>/dev/null || true
  fi
}

ensure_native() {
  local manifest=android/app/src/main/AndroidManifest.xml
  if [ ! -d android ] || [ ! -f "$manifest" ]; then
    say "android/ missing"
    prebuild
    return
  fi
  # app.json and plugins/ describe the manifest; a change to either is only real once regenerated.
  if [ -n "$(find app.json plugins -newer "$manifest" 2>/dev/null | head -1)" ]; then
    say "app.json or plugins/ changed since the manifest"
    prebuild
  fi
}

# The APK carries the native modules and the manifest of the moment it was built. A new dependency
# or an app.json edit lands in JS instantly and in the APK not at all, so installing yesterday's
# APK gives a green `verify` and an app that dies on launch — `Cannot find native module …`.
# These are the inputs that can only reach the device through a rebuild. `modules/` is among them:
# a new method on a local Expo module, or a line in its own AndroidManifest, reaches the device
# only through the merge that assembleDebug does — over Metro it simply is not there, and the call
# fails at runtime while everything else looks right.
#
# `app.config.js` is here for a quieter version of the same trap, and it cost a smoke run to find:
# expo-constants embeds the *resolved* config into the APK as `assets/app.config` at build time,
# and `Constants.expoConfig` reads that file — not the manifest Metro serves. So a репорт про
# помилку filed against a reused APK named «Коміт: unknown» while `npx expo config` resolved the
# real one. Config that only feeds `extra` still reaches the device solely through a rebuild.
apk_is_stale() {
  [ -f "$APK" ] || return 0
  local newer
  newer=$(find package.json app.json app.config.js plugins modules -newer "$APK" 2>/dev/null \
    -not -path 'modules/*/android/build/*' | head -1)
  [ -n "$newer" ] && { say "$newer is newer than the APK — rebuilding"; return 0; }
  return 1
}

build() {
  ensure_native
  # Only the ABI the device actually uses — a four-ABI build is ~4× the work.
  local abi; abi=$(adb shell getprop ro.product.cpu.abi 2>/dev/null | tr -d '\r'); abi=${abi:-arm64-v8a}
  say "gradle assembleDebug ($abi)"
  (cd android && ./gradlew assembleDebug -PreactNativeArchitectures="$abi" --console=plain)
}

install() {
  # `if`, not `&&`: under `set -e` a false tail of an `&&` list would end the script.
  if apk_is_stale; then build; fi
  say "installing $APK"
  adb install -r -d "$APK"
}

metro() {
  if curl -s "http://localhost:$METRO_PORT/status" 2>/dev/null | grep -q packager; then
    say "Metro already running on $METRO_PORT"
  else
    say "starting Metro (log: $RUN_DIR/metro.log)"
    npx expo start --port "$METRO_PORT" >"$RUN_DIR/metro.log" 2>&1 &
    echo $! >"$RUN_DIR/metro.pid"
    # Bounded: if Metro dies on startup this loop would otherwise spin forever.
    local waited=0
    until curl -s "http://localhost:$METRO_PORT/status" 2>/dev/null | grep -q packager; do
      sleep 1; waited=$((waited + 1))
      [ "$waited" -lt 90 ] || { tail -20 "$RUN_DIR/metro.log"; die "Metro did not come up in ${waited}s"; }
    done
  fi
  # The debug build fetches its bundle from localhost on the device.
  adb reverse "tcp:$METRO_PORT" "tcp:$METRO_PORT" >/dev/null
}

# The touchscreen's event node, as the kernel names it. Asked of the device rather than assumed:
# an AVD and a plugged-in phone do not agree on the number, and a wrong node sends taps into the
# void with no error at all.
touch_device() {
  adb shell getevent -pl 2>/dev/null \
    | awk '/^add device/ {dev=$4} /ABS_MT_POSITION_X/ {print dev; exit}'
}

# Two fingers down at (x1,y1) and (x2,y2), held for MS, optionally moved by (dx,dy) first, then up.
#
# Multitouch protocol B: each finger owns a slot with a tracking id, and a slot whose id is set to
# -1 is a finger lifted. SYN_REPORT (0 0 0) is what commits a batch of events as one frame, so it
# comes after every group — without it the kernel sees nothing at all.
two_finger_hold() {
  local x1=$1 y1=$2 x2=$3 y2=$4 ms=$5 dx=${6:-0} dy=${7:-0}
  local dev
  dev=$(touch_device) || true
  [ -n "$dev" ] || die "no touchscreen event node found (getevent -pl); use the handle instead — see design D12"

  # EV_ABS=3, EV_SYN=0. ABS_MT_SLOT=0x2f, ABS_MT_TRACKING_ID=0x39, POSITION_X=0x35, POSITION_Y=0x36.
  adb shell "
    sendevent $dev 3 47 0; sendevent $dev 3 57 1001
    sendevent $dev 3 53 $x1; sendevent $dev 3 54 $y1
    sendevent $dev 3 47 1; sendevent $dev 3 57 1002
    sendevent $dev 3 53 $x2; sendevent $dev 3 54 $y2
    sendevent $dev 0 0 0
  "
  if [ "$dx" -ne 0 ] || [ "$dy" -ne 0 ]; then
    # Moved in a few steps rather than one jump, so the recognizer sees travel and cancels rather
    # than seeing a teleport it might discard as noise.
    local step
    for step in 1 2 3 4; do
      adb shell "
        sendevent $dev 3 47 0; sendevent $dev 3 53 $((x1 + dx * step / 4)); sendevent $dev 3 54 $((y1 + dy * step / 4))
        sendevent $dev 3 47 1; sendevent $dev 3 53 $((x2 + dx * step / 4)); sendevent $dev 3 54 $((y2 + dy * step / 4))
        sendevent $dev 0 0 0
      "
    done
  fi
  sleep "$(awk -v ms="$ms" 'BEGIN { print ms / 1000 }')"
  adb shell "
    sendevent $dev 3 47 0; sendevent $dev 3 57 -1
    sendevent $dev 3 47 1; sendevent $dev 3 57 -1
    sendevent $dev 0 0 0
  "
}

launch() {
  say "launching $PACKAGE"
  adb shell am force-stop "$PACKAGE"
  adb shell monkey -p "$PACKAGE" -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1
}

case "${1:-up}" in
  up)      ensure_device; install; metro; launch; say "up — screenshot with: scripts/android.sh shot" ;;
  build)   ensure_device; build ;;
  install) ensure_device; install ;;
  metro)   ensure_device; metro ;;
  launch)  ensure_device; launch ;;
  reset)   ensure_device; say "clearing app data"; adb shell pm clear "$PACKAGE"; launch ;;
  shot)    ensure_device; out=${2:-$RUN_DIR/shot.png}; adb exec-out screencap -p >"$out"; say "wrote $out" ;;
  tap)     ensure_device; adb shell input tap "${2:?x}" "${3:?y}" ;;
  # `input text` takes no spaces and no Cyrillic; %s stands in for a space, and non-ASCII goes
  # through the IME clipboard instead. Keep smoke-test input ASCII where you can.
  text)    ensure_device; adb shell input text "$(printf '%s' "${2:?text}" | sed 's/ /%s/g')" ;;
  key)     ensure_device; adb shell input keyevent "${2:?keycode}" ;;
  # One finger, dragged. `input swipe` is enough for every scroll and flick §8 needs, and unlike
  # the two-finger drivers below it needs no knowledge of the touchscreen device node.
  swipe)   ensure_device
           adb shell input swipe "${2:?x1}" "${3:?y1}" "${4:?x2}" "${5:?y2}" "${6:-300}" ;;
  # Two fingers held still — the репорт gesture. `adb shell input` has no multi-touch at all, so
  # this goes to the touchscreen's own event node through `sendevent`, multitouch protocol B: two
  # tracking slots down, a hold, both up. Default 1400 ms, comfortably past GESTURE.minDurationMs
  # (1200) without being so long that a test waits on it.
  twofinger) ensure_device; two_finger_hold "${2:?x1}" "${3:?y1}" "${4:?x2}" "${5:?y2}" "${6:-1400}" ;;
  # Two fingers that travel. It must start nothing: the recognizer cancels past GESTURE.maxDistanceDp
  # (24), and scenario 8.5 is what proves that on a device rather than in a comment.
  twodrag) ensure_device
           two_finger_hold "${2:?x1}" "${3:?y1}" "${4:?x2}" "${5:?y2}" "${8:-1400}" "${6:?dx}" "${7:?dy}" ;;
  # A bounded dump, never a stream: plain `adb logcat` follows the device forever and the caller
  # (an agent, a hook) waits with it for hours. `-d` reads the buffer to its end and exits; the
  # tail is ours rather than logcat's `-t`, which counts unfiltered lines and so returns almost
  # nothing once the app's tags are filtered out of a noisy window.
  logs)    ensure_device
           adb logcat -d -s ReactNative:V ReactNativeJS:V AndroidRuntime:E expo:V | tail -n "${2:-200}" ;;
  stop)    [ -f "$RUN_DIR/metro.pid" ] && kill "$(cat "$RUN_DIR/metro.pid")" 2>/dev/null || true
           rm -f "$RUN_DIR/metro.pid"; (cd android 2>/dev/null && ./gradlew --stop) || true; say "stopped" ;;
  *)       die "unknown command: $1 (see the header of $0)" ;;
esac
